---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: medicure
    name: medicure
spec:
      containers:
      - name: medicure
        image: ankit9090/medicure-image:latest
        ports:
        - containerPort: 8082

     
