apiVersion: v1
kind: Pod
metadata:
  name: medicure-image
  labels:
    app: medicure-image
spec:
      containers:
      - name: medicure-image
        image: ankit9090/medicure-image:latest
        ports:
        - containerPort: 8082
