apiVersion: v1
kind: Pod
metadata:
  name: nodeapp 
  labels:
    app: nodeapp
spec:
      containers:
      - name: nodeapp
        image: ankit9090/medicure-image:latest
        ports:
        - containerPort: 8082