apiVersion: v1
kind: Service
metadata:
  name: medicure-image
spec:
  selector:
    app: medicure-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
